version: '3.8'

services:
  gateway:
    build: ./gateway_server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - USER_SERVICE_URL=http://user:3001
      - EVENT_SERVICE_URL=http://event:3002
      - JWT_SECRET=nexon-assignment-secret-key-2024
    depends_on:
      - user
      - event
      - mongodb
    networks:
      - app-network

  user:
    build: ./user_server
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/nexon
      - JWT_SECRET=nexon-assignment-secret-key-2024
    networks:
      - app-network

  event:
    build: ./event_server
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MONGO_URI=mongodb://mongodb:27017/nexon
      - JWT_SECRET=nexon-assignment-secret-key-2024
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 